package pojos;
// Generated Jan 21, 2018 12:34:14 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Content generated by hbm2java
 */
@Entity
@Table(name = "content", catalog = "techingress")
public class Content implements java.io.Serializable {

	private int cid;
	private Users users;
	private String cname;
	private Date cuploadtime;
	private Set<Users> userses = new HashSet<Users>(0);

	public Content() {
	}

	public Content(int cid) {
		this.cid = cid;
	}

	public Content(int cid, Users users, String cname, Date cuploadtime, Set<Users> userses) {
		this.cid = cid;
		this.users = users;
		this.cname = cname;
		this.cuploadtime = cuploadtime;
		this.userses = userses;
	}

	@Id

	@Column(name = "cid", unique = true, nullable = false)
	public int getCid() {
		return this.cid;
	}

	public void setCid(int cid) {
		this.cid = cid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "cName", length = 20)
	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "cUploadtime", length = 10)
	public Date getCuploadtime() {
		return this.cuploadtime;
	}

	public void setCuploadtime(Date cuploadtime) {
		this.cuploadtime = cuploadtime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "content")
	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

}
