package pojos;
// Generated Jan 21, 2018 12:34:14 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Qna generated by hbm2java
 */
@Entity
@Table(name = "qna", catalog = "techingress")
public class Qna implements java.io.Serializable {

	private int qnaId;
	private Discussionforum discussionforum;
	private Users users;
	private String question;
	private String ans;
	private Date ansdate;
	private Date quesdate;

	public Qna() {
	}

	public Qna(int qnaId) {
		this.qnaId = qnaId;
	}

	public Qna(int qnaId, Discussionforum discussionforum, Users users, String question, String ans, Date ansdate,
			Date quesdate) {
		this.qnaId = qnaId;
		this.discussionforum = discussionforum;
		this.users = users;
		this.question = question;
		this.ans = ans;
		this.ansdate = ansdate;
		this.quesdate = quesdate;
	}

	@Id

	@Column(name = "QNA_id", unique = true, nullable = false)
	public int getQnaId() {
		return this.qnaId;
	}

	public void setQnaId(int qnaId) {
		this.qnaId = qnaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ForumId")
	public Discussionforum getDiscussionforum() {
		return this.discussionforum;
	}

	public void setDiscussionforum(Discussionforum discussionforum) {
		this.discussionforum = discussionforum;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "Question", length = 200)
	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	@Column(name = "Ans", length = 500)
	public String getAns() {
		return this.ans;
	}

	public void setAns(String ans) {
		this.ans = ans;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Ansdate", length = 10)
	public Date getAnsdate() {
		return this.ansdate;
	}

	public void setAnsdate(Date ansdate) {
		this.ansdate = ansdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Quesdate", length = 10)
	public Date getQuesdate() {
		return this.quesdate;
	}

	public void setQuesdate(Date quesdate) {
		this.quesdate = quesdate;
	}

}
