package pojos;
// Generated Jan 21, 2018 12:34:14 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usergroup generated by hbm2java
 */
@Entity
@Table(name = "usergroup", catalog = "techingress")
public class Usergroup implements java.io.Serializable {

	private int groupId;
	private Users users;
	private String groupName;
	private Date createTime;
	private Set<Users> userses = new HashSet<Users>(0);

	public Usergroup() {
	}

	public Usergroup(int groupId) {
		this.groupId = groupId;
	}

	public Usergroup(int groupId, Users users, String groupName, Date createTime, Set<Users> userses) {
		this.groupId = groupId;
		this.users = users;
		this.groupName = groupName;
		this.createTime = createTime;
		this.userses = userses;
	}

	@Id

	@Column(name = "group_id", unique = true, nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "group_Name", length = 20)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_time", length = 10)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usergroup")
	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

}
